function Build_MOC_Output(input_file, C_matrix)

% This function takes in the values of stress and the C matrix that
% is generated by the MOC function, and outputs them to a file. MOC.m is
% written by Michael Kaplan and Rehan Nawaz with the assistance of
% Professor Anthony M. Waas.
%
% by Rehan Nawaz
% -------------------------------------------------------------------------

% Create the filename for the output
filename = strcat(input_file, '.moco');
fid = fopen(filename, 'a');

% create the input header
fprintf(fid, '%% MOC Output: %s\n', filename);
time = datestr(clock);
fprintf(fid,'%% Created: %s\n%%\n',time);

%--------------------------------------------------------------------------
%                               C MATRIX
%--------------------------------------------------------------------------

fprintf(fid,'*C Matrix: \n');

fprintf(fid, 'C_matrix=%10.6e', \n);




